name: Build and Publish storybook to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js and pnpm as specified in package.json
        uses: volta-cli/action@v4

      - name: Install pinned pnpm with Volta
        run: volta install pnpm

      - name: Deploy Storybook to GitHub Pages
        id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static
          install_command: pnpm install --frozen-lockfile
          build_command: pnpm build-storybook
