name: Release
on:
  push:
    branches: [master, release]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn as specified in package.json
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        # Note that semantic-release reads release.config.js
        run: npx semantic-release
